config/routes.rb
Rails.application.routes.draw do
  resources :portfoliios,except: [:show]
  get 'c-items', to: 'portfoliios#c'
  get 'portfoliios/:id' ,to: 'portfoliios#show'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :topic
    enum status: { draft: 0, published: 1}
    extend FriendlyId
    friendly_id :title, use: :slugged

    validates_presence_of :title, :body
end

app/models/portfoliio.rb
class Portfoliio < ApplicationRecord
    validates_presence_of :title, :body, :main_image, :thumb_image
    
    def self.c_programming
        where(subtitle: "C programing")
    end

    # or
    # scope :c_programming, -> { where(subtitle: 'C programing') }
end

app/models/skill.rb
class Skill < ApplicationRecord
    validates_presence_of :title, :percent_utilized
end

app/models/topic.rb
class Topic < ApplicationRecord
    has_many :blogs
    validates_presence_of :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end
    redirect_to blogs_url, notice: "Post status has been updated."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @blogs = Blog.all
    @skills = Skill.all
  end

  def about
  end

  def contact
  end
end

app/controllers/portfoliios_controller.rb
class PortfoliiosController < ApplicationController
  def index
      @portfolio_items = Portfoliio.all
      # Portfoliio.c_programming
      # Portfoliio.where(subtitle: "C programming") or check model
  end

  def c
    @c_portfolio_items = Portfoliio.c_programming
      # Portfoliio.where(subtitle: "C programming") or check model
  end
  def new
    @portfolio_item = Portfoliio.new
  end
  def create
    @portfolio_item = Portfoliio.new(params.require(:portfoliio).permit(:title, :subtitle, :body))  
    respond_to do |format|
      if @portfolio_item.save
          format.html {redirect_to portfoliios_path, notice: "added"}
      else
          format.html{render :new}  
      end
    end
  end
  def edit
    @portfolio_item = Portfoliio.find(params[:id])
  end
  def update
    @portfolio_item = Portfoliio.find(params[:id])
    respond_to do |format|
      if @portfolio_item.update(params.require(:portfoliio).permit(:title, :subtitle, :body))
        format.html { redirect_to portfoliios_path, notice: 'portfolio was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end
  def show
    @portfolio_item = Portfoliio.find(params[:id])
  end
  def destroy
    @portfolio_item = Portfoliio.find(params[:id])
    @portfolio_item.destroy
    respond_to do |format|
          format.html { redirect_to portfoliios_url, notice: 'portfolio was removed.' }
  end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfoliios_helper.rb
module PortfoliiosHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title.upcase %></td>
        <td><%= blog.body %></td>
        <td><%= link_to blog.status, toggle_status_blog_path(blog) %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<h2>Blog</h2>
<%= @blogs.inspect %>

<h2>Skill</h2>
<%= @skills.inspect %>

app/views/portfoliios/c.html.erb
<h1>C portfolio</h1>

<%= link_to "Create New", new_portfoliio_url %><br/>

<% @c_portfolio_items.each do |p| %>
<p><%=  link_to  p.title , portfoliio_path(p.id) %></p>
<p><%= p.subtitle %></p>
<p><%= p.body %></p>
<%# <%= p.main_image  %>
<p><%= image_tag p.thumb_image unless p.thumb_image.nil? %></p>
<%# <%= link_to "Show", portfoliio_path(p.id) %> 
<p><%= link_to "Edit", edit_portfoliio_path(p.id) %></p>
<p><%= link_to "Delete", portfoliio_path(p),method: :delete, data:{confirm: "Are you sure ?"} %></p>
<%# <a href="portfoliios/<%= p.id /edit">Edithref</a> %>
<% end %>

app/views/portfoliios/edit.html.erb
<h1>Edit</h1>

<%= form_for(@portfolio_item) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

    <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfoliios/index.html.erb
<h1>Portfolio Items</h1>

<%= link_to "Create New Item", new_portfoliio_path %>

<%# <%= new_portfoliio_path %>
<%# <%= new_portfoliio_url %> 


<table>
<tr>
<th>Title</th>
<th>Sub-Title</th>
<th>Body</th>
<%# <th>Main-Image</th> %>
<th>Thumb-Image</th>
</tr>
<% @portfolio_items.each do |p| %>
<tr>
<td><%=  link_to  p.title , portfoliio_path(p.id) %></td>
<td><%= p.subtitle %></td>
<td><%= p.body %></td>
<%# <td><%= p.main_image</td>  %>
<td><%= image_tag p.thumb_image unless p.thumb_image.nil? %></td>
<%# <td><%= link_to "Show", portfoliio_path(p.id) %></td> 
<td><%= link_to "Edit", edit_portfoliio_path(p.id) %></td>
<td><%= link_to "Delete", portfoliio_path(p),method: :delete, data:{confirm: "Are you sure ?"} %></td>
<%# <td><a href="portfoliios/<%= p.id /edit">Edithref</a></td> %>
</tr>
<% end %>

app/views/portfoliios/new.html.erb
<h1>New Html</h1>

<%= form_for(@portfolio_item) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

    <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfoliios/show.html.erb
<h1><%= image_tag @portfolio_item.main_image %></h1>

<h1><%= @portfolio_item.title %></h1>
<p><%= @portfolio_item.subtitle %></p>
<p><%= @portfolio_item.body %></p>